# Generated by Django 5.1.4 on 2025-01-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название категории"),
                ),
                (
                    "description",
                    models.CharField(max_length=150, verbose_name="Описание категории"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название товара"),
                ),
                (
                    "description",
                    models.CharField(max_length=150, verbose_name="Описание товара"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/", verbose_name="Изображение товара"
                    ),
                ),
                (
                    "category",
                    models.CharField(max_length=150, verbose_name="Категория товара"),
                ),
                ("price", models.CharField(max_length=150, verbose_name="Цена товара")),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата создания товара"
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now_add=True,
                        verbose_name="Дата последнего изменения товара",
                    ),
                ),
            ],
        ),
    ]
