# Generated by Django 4.2.2 on 2025-03-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0003_product_is_published_product_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(verbose_name="Цена товара"),
        ),
    ]
